export const GET_SEARCHED_REPOSITORIES_REQUEST = 'GET_SEARCHED_REPOSITORIES_REQUEST';
export const GET_SEARCHED_REPOSITORIES_SUCCESS = 'GET_SEARCHED_REPOSITORIES_SUCCESS';
export const GET_SEARCHED_REPOSITORIES_ERROR = 'GET_SEARCHED_REPOSITORIES_ERROR';

export const SET_SEARCHED_REPOSITORIES_PAGE = 'SET_SEARCHED_REPOSITORIES_PAGE';
