export const GET_TOP_REPOSITORIES_REQUEST = 'GET_TOP_REPOSITORIES_REQUEST';
export const GET_TOP_REPOSITORIES_SUCCESS = 'GET_TOP_REPOSITORIES_SUCCESS';
export const GET_TOP_REPOSITORIES_ERROR = 'GET_TOP_REPOSITORIES_ERROR';
